import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Make sure this is generated by FlutterFire CLI

// Screens
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/home_screen.dart';
import 'screens/complaint_screen.dart';
import 'screens/my_complaints_screen.dart';
import 'screens/admin_complaints_screen.dart';

void main() async {
  // 1. THIS LINE IS CRITICAL. It must be called before Firebase.initializeApp()
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase init failed: $e");
  }

  // 3. Run the App
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Jharkhand CivicFix',
      debugShowCheckedModeBanner: false,
      
      // 🔥 GLOBAL THEME: Matches your UI/UX Screenshots
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF2D6A4F), // Jharkhand Green
          primary: const Color(0xFF2D6A4F),
          secondary: const Color(0xFF40916C),
          surface: const Color(0xFFF8F9FA), // Light gray background
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF2D6A4F),
          foregroundColor: Colors.white,
          elevation: 0,
          centerTitle: true,
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFFF1F3F4),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF52B788), // Brighter green for primary actions
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 54),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          ),
        ),
      ),
      
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(),
        '/home': (context) => const HomeScreen(),
        '/complaint': (context) => const ComplaintScreen(), // Added missing route
        '/my-complaints': (context) => const MyComplaintsScreen(), // Added missing route
        '/admin-complaints': (context) => const AdminComplaintsScreen(),
      },
    );
  }
}